const b2bData = {
  "total": 173,
  "by_client": {
    "Aqua B2C": 76,
    "ANTA": 33,
    "Con Cưng": 64
  },
  "by_warehouse": [
    {
      "warehouse": "Đông Thọ - Thanh Hoá",
      "count": 26
    },
    {
      "warehouse": "Thủ Đức - HCM",
      "count": 19
    },
    {
      "warehouse": "Tân Tạo - HCM",
      "count": 18
    },
    {
      "warehouse": "Vinh - Nghệ An",
      "count": 15
    },
    {
      "warehouse": "Quảng Ngãi - Quảng Ngãi",
      "count": 10
    },
    {
      "warehouse": "Bắc Từ Liêm",
      "count": 7
    },
    {
      "warehouse": "Long Biên",
      "count": 7
    },
    {
      "warehouse": "Tân Bình - HCM",
      "count": 5
    },
    {
      "warehouse": "Thanh Oai",
      "count": 5
    },
    {
      "warehouse": "Liên Chiểu - Đà Nẵng",
      "count": 5
    },
    {
      "warehouse": "Nhà Bè - HCM",
      "count": 4
    },
    {
      "warehouse": "An Dương - Hải Phòng",
      "count": 4
    },
    {
      "warehouse": "Ân Thi - Hưng Yên",
      "count": 4
    },
    {
      "warehouse": "TP Thái Nguyên - Thái Nguyên",
      "count": 4
    },
    {
      "warehouse": "Hoài Đức",
      "count": 3
    },
    {
      "warehouse": "Tiên Du - Bắc Ninh",
      "count": 3
    },
    {
      "warehouse": "Bình Xuyên - Vĩnh Phúc",
      "count": 3
    },
    {
      "warehouse": "Việt Yên - Bắc Giang",
      "count": 3
    },
    {
      "warehouse": "Tân Bình - Hải Dương",
      "count": 2
    },
    {
      "warehouse": "TP Lào Cai - Lào Cai",
      "count": 2
    },
    {
      "warehouse": "TP Biên Hoà - Đồng Nai",
      "count": 2
    },
    {
      "warehouse": "Hồ Chí Minh",
      "count": 2
    },
    {
      "warehouse": "Dĩ An - Bình Dương",
      "count": 2
    },
    {
      "warehouse": "Thuận An - Bình Dương",
      "count": 2
    },
    {
      "warehouse": "Bưu Cục Tân Thanh-Điện Biên Phủ-Điện Biên",
      "count": 1
    },
    {
      "warehouse": "Bưu Cục Ngã 3 Bãy Vòng 973-Đặc Khu Phú Quốc-Kiên Giang",
      "count": 1
    },
    {
      "warehouse": "Đức Long -  Hà Nội",
      "count": 1
    },
    {
      "warehouse": "Thanh Trì",
      "count": 1
    },
    {
      "warehouse": "Nho Quan - Ninh Bình",
      "count": 1
    },
    {
      "warehouse": "TP Cà Mau - Cà Mau",
      "count": 1
    },
    {
      "warehouse": "Hương Thủy - Huế",
      "count": 1
    },
    {
      "warehouse": "Quy Nhơn - Bình Định",
      "count": 1
    },
    {
      "warehouse": "Tuy Hoà - Phú Yên",
      "count": 1
    },
    {
      "warehouse": "TP Đồng Xoài - Bình Phước",
      "count": 1
    },
    {
      "warehouse": "Đức Hòa - Long An",
      "count": 1
    },
    {
      "warehouse": "TX Cai Lậy - Tiền Giang",
      "count": 1
    },
    {
      "warehouse": "Phan Rang - Ninh Thuận",
      "count": 1
    },
    {
      "warehouse": "Thạch Linh - Hà Tĩnh",
      "count": 1
    },
    {
      "warehouse": "TP Lạng Sơn - Lạng Sơn",
      "count": 1
    },
    {
      "warehouse": "TP Vũng Tàu - BRVT",
      "count": 1
    }
  ],
  "orders": [
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Liên Chiểu - Đà Nẵng",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYWRAKFD",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Đà Nẵng - Quận Hải Châu",
      "inbound_date": "2026-05-07",
      "storage_days": "19",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYT9HN4Y",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Tân Phú",
      "inbound_date": "2026-05-17",
      "storage_days": "9",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYT9HN9P",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận 3",
      "inbound_date": "2026-05-17",
      "storage_days": "9",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYT9HNHY",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Tân Phú",
      "inbound_date": "2026-05-17",
      "storage_days": "9",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYT9HNP3",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Tân Phú",
      "inbound_date": "2026-05-17",
      "storage_days": "9",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYT9HNPW",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Bình Tân",
      "inbound_date": "2026-05-17",
      "storage_days": "9",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYT9H6HE",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Bình Thạnh",
      "inbound_date": "2026-05-17",
      "storage_days": "9",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Hương Thủy - Huế",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT9UFA6",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Thừa Thiên Huế - Quận Thuận Hóa",
      "inbound_date": "2026-05-17",
      "storage_days": "9",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTGVGPC",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Quận 1",
      "inbound_date": "2026-05-19",
      "storage_days": "7",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTPL7GA",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Thành Phố Thủ Đức",
      "inbound_date": "2026-05-20",
      "storage_days": "6",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Hoài Đức",
      "pic": "Lê Như Tánh",
      "order_code": "GYT9H6WQ",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hà Nội - Quận Nam Từ Liêm",
      "inbound_date": "2026-05-20",
      "storage_days": "6",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTBL8QB",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận 9",
      "inbound_date": "2026-05-21",
      "storage_days": "5",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Long Biên",
      "pic": "Lê Như Tánh",
      "order_code": "GYTBXN7C",
      "action": "giao",
      "client": "ANTA",
      "address": "Hà Nội - Quận Hai Bà Trưng",
      "inbound_date": "2026-05-21",
      "storage_days": "5",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Bưu Cục Tân Thanh-Điện Biên Phủ-Điện Biên",
      "pic": "Vũ Khắc Việt",
      "order_code": "GYTB4HBM",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Điện Biên - Thành phố Điện Biên Phủ",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Bình - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYT4P347",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Gò Vấp",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTB38MH",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Bình Tân",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTBTWMW",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Thành Phố Thủ Đức",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTDKKGP",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Thành Phố Thủ Đức",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Bắc Từ Liêm",
      "pic": "Lê Như Tánh",
      "order_code": "GYT3CV9G",
      "action": "giao",
      "client": "ANTA",
      "address": "Hà Nội - Quận Đống Đa",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Bắc Từ Liêm",
      "pic": "Lê Như Tánh",
      "order_code": "GYTB4H8X",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hà Nội - Quận Bắc Từ Liêm",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Bắc Từ Liêm",
      "pic": "Lê Như Tánh",
      "order_code": "GYTB4XYN",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hà Nội - Quận Ba Đình",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Hoài Đức",
      "pic": "Lê Như Tánh",
      "order_code": "GYTB4A94",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hà Nội - Quận Thanh Xuân",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thanh Oai",
      "pic": "Lê Như Tánh",
      "order_code": "GYTDF7N6",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Hà Nội - Huyện Chương Mỹ",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thanh Trì",
      "pic": "Lê Như Tánh",
      "order_code": "GYT3PATP",
      "action": "giao",
      "client": "ANTA",
      "address": "Hà Nội - Quận Hoàng Mai",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tiên Du - Bắc Ninh",
      "pic": "Nguyễn Mạnh Hưng",
      "order_code": "GYTB34WY",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Bắc Ninh - Thành phố Bắc Ninh",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Ân Thi - Hưng Yên",
      "pic": "Nguyễn Sơn Tuấn",
      "order_code": "GYTNAK9L",
      "action": "giao",
      "client": "ANTA",
      "address": "Hưng Yên - Thị xã Mỹ Hào",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "TP Biên Hoà - Đồng Nai",
      "pic": "Trần Như Long",
      "order_code": "GYT3VQCQ",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Đồng Nai - Thành phố Biên Hòa",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3NL4V",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Thanh Hóa - Huyện Hà Trung",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3NLAA",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Thanh Hóa - Huyện Nông Cống",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3NLAD",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Thanh Hóa - Huyện Vĩnh Lộc",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTBRFAA",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Thanh Hóa - Huyện Hà Trung",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Quy Nhơn - Bình Định",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTP3V9W",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Bình Định - Thành phố Quy Nhơn",
      "inbound_date": "2026-05-22",
      "storage_days": "4",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYT3LACX",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Quận 10",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYT3HLDE",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Bình Thạnh",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTBRFYK",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận 9",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTBWNUU",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Thành Phố Thủ Đức",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTNBVCN",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Thành Phố Thủ Đức",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Bắc Từ Liêm",
      "pic": "Lê Như Tánh",
      "order_code": "GYTPNAHP",
      "action": "giao",
      "client": "ANTA",
      "address": "Hà Nội - Quận Nam Từ Liêm",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Long Biên",
      "pic": "Lê Như Tánh",
      "order_code": "GYT3NLK7",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hà Nội - Quận Hai Bà Trưng",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Long Biên",
      "pic": "Lê Như Tánh",
      "order_code": "GYT3NLNY",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hà Nội - Quận Long Biên",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "An Dương - Hải Phòng",
      "pic": "Đào Anh Duy",
      "order_code": "GYT3NL8L",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hải Phòng - Quận Hải An",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Nho Quan - Ninh Bình",
      "pic": "Nguyễn Mạnh Hưng",
      "order_code": "GYT3TP4N",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Ninh Bình - Huyện Kim Sơn",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "TP Cà Mau - Cà Mau",
      "pic": "Trần Hoàng An Khang",
      "order_code": "GYTBRFYL",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Cà Mau - Huyện Trần Văn Thời",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT4TCGP",
      "action": "giao",
      "client": "ANTA",
      "address": "Thanh Hóa - Thành phố Thanh Hóa",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTBRFYU",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Thanh Hóa - Huyện Hậu Lộc",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tuy Hoà - Phú Yên",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTB3Y4C",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Phú Yên - Thành phố Tuy Hòa",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTBF99Q",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Nghệ An - Thị xã Hoàng Mai",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTPFWY7",
      "action": "giao",
      "client": "ANTA",
      "address": "Nghệ An - Thị xã Thái Hòa",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTPLUMG",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Nghệ An - Thị xã Hoàng Mai",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTDUYF8",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Huyện Bình Chánh",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Long Biên",
      "pic": "Lê Như Tánh",
      "order_code": "GYTBWPD6",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Hà Nội - Quận Long Biên",
      "inbound_date": "2026-05-23",
      "storage_days": "3",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Nhà Bè - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTK6BCF",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Huyện Nhà Bè",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Bình - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTK36XM",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Phú Nhuận",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTK36XD",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận 1",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTVM8PT",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Quận Tân Phú",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "An Dương - Hải Phòng",
      "pic": "Đào Anh Duy",
      "order_code": "GYT3HML6",
      "action": "giao",
      "client": "ANTA",
      "address": "Hải Phòng - Quận Lê Chân",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Bình - Hải Dương",
      "pic": "Đào Anh Duy",
      "order_code": "GYT36LHQ",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hải Dương - Huyện Gia Lộc",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Tân Bình - Hải Dương",
      "pic": "Đào Anh Duy",
      "order_code": "GYT36LPU",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hải Dương - Huyện Gia Lộc",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Ân Thi - Hưng Yên",
      "pic": "Nguyễn Sơn Tuấn",
      "order_code": "GYT3NLPN",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hưng Yên - Huyện Ân Thi",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Ân Thi - Hưng Yên",
      "pic": "Nguyễn Sơn Tuấn",
      "order_code": "GYT4X8HY",
      "action": "giao",
      "client": "ANTA",
      "address": "Hưng Yên - Thị xã Mỹ Hào",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Ân Thi - Hưng Yên",
      "pic": "Nguyễn Sơn Tuấn",
      "order_code": "GYTNH38K",
      "action": "giao",
      "client": "ANTA",
      "address": "Hưng Yên - Thị xã Mỹ Hào",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Bình Xuyên - Vĩnh Phúc",
      "pic": "Nguyễn Sơn Tuấn",
      "order_code": "GYT3NLH7",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Vĩnh Phúc - Huyện Lập Thạch",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Long Biên",
      "pic": "Lê Như Tánh",
      "order_code": "GYT3XGWH",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Hà Nội - Huyện Gia Lâm",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Long Biên",
      "pic": "Lê Như Tánh",
      "order_code": "GYT3XGWY",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Hà Nội - Huyện Sóc Sơn",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Thanh Oai",
      "pic": "Lê Như Tánh",
      "order_code": "GYT446NQ",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hà Nội - Huyện Chương Mỹ",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Tiên Du - Bắc Ninh",
      "pic": "Nguyễn Mạnh Hưng",
      "order_code": "GYTBTWH3",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Bắc Ninh - Huyện Quế Võ",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3X7AC",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Hậu Lộc",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3X7XR",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Thành phố Thanh Hóa",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGHE",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Thiệu Hóa",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGTY",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Cẩm Thủy",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGXA",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Triệu Sơn",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGXC",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Nông Cống",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGXD",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Thành phố Thanh Hóa",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGXF",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Hậu Lộc",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGXN",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Hậu Lộc",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGXT",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Thọ Xuân",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGXV",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Thọ Xuân",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGH6",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Nghệ An - Huyện Yên Thành",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGH7",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Nghệ An - Huyện Quỳnh Lưu",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGHG",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Nghệ An - Thành phố Vinh",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGTA",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Nghệ An - Huyện Quỳnh Lưu",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGTE",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Nghệ An - Thị xã Thái Hòa",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT3XGTX",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Nghệ An - Huyện Diễn Châu",
      "inbound_date": "2026-05-24",
      "storage_days": "2",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Bưu Cục Ngã 3 Bãy Vòng 973-Đặc Khu Phú Quốc-Kiên Giang",
      "pic": "Nguyễn Đại Danh",
      "order_code": "GYT9HN8G",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Kiên Giang - Thành phố Phú Quốc",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYT48U39",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Thành Phố Thủ Đức",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYT4ACLL",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Thành Phố Thủ Đức",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTKNWGV",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Thành Phố Thủ Đức",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTNBVCH",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Thành Phố Thủ Đức",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTTDQ8",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Thành Phố Thủ Đức",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Bắc Từ Liêm",
      "pic": "Lê Như Tánh",
      "order_code": "GYTPQNPW",
      "action": "giao",
      "client": "ANTA",
      "address": "Hà Nội - Quận Đống Đa",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Bắc Từ Liêm",
      "pic": "Lê Như Tánh",
      "order_code": "GYTT3DRB",
      "action": "giao",
      "client": "ANTA",
      "address": "Hà Nội - Quận Ba Đình",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Đức Long -  Hà Nội",
      "pic": "Lê Như Tánh",
      "order_code": "GYTKB33E",
      "action": "giao",
      "client": "ANTA",
      "address": "Hà Nội - Quận Hai Bà Trưng",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Long Biên",
      "pic": "Lê Như Tánh",
      "order_code": "GYTKB9RQ",
      "action": "giao",
      "client": "ANTA",
      "address": "Hà Nội - Quận Hai Bà Trưng",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "TP Lào Cai - Lào Cai",
      "pic": "Nguyễn Sơn Tuấn",
      "order_code": "GYTBNGEX",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Lào Cai - Huyện Bát Xát",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "TP Biên Hoà - Đồng Nai",
      "pic": "Trần Như Long",
      "order_code": "GYTTMB9F",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Đồng Nai - Thành phố Biên Hòa",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTNK7QM",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Thanh Hóa - Huyện Thọ Xuân",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTNKFMD",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Thanh Hóa - Huyện Thọ Xuân",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT36LHC",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Nghệ An - Huyện Diễn Châu",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "1: trong hôm nay",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTBRF8V",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Nghệ An - Huyện Quỳ Hợp",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Hồ Chí Minh",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTMBGC",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Huyện Hóc Môn",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Hồ Chí Minh",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTX3DV",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Huyện Củ Chi",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Nhà Bè - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYT4AF3F",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Quận 7",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Nhà Bè - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTX3GG",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận 7",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Nhà Bè - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTXBET",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận 7",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Tân Bình - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTX33F",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Gò Vấp",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Tân Bình - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTX3FB",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận 12",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Tân Bình - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTX3HE",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Tân Bình",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTMBCC",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận 8",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTMBCW",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Tân Phú",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTX346",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Tân Phú",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTX3BG",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Tân Phú",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTX3LA",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận 10",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTKHDCC",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Quận Bình Thạnh",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTMB9R",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Bình Thạnh",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTX37L",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Quận Bình Thạnh",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTX3PT",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Thành Phố Thủ Đức",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Thủ Đức - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTX3TC",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hồ Chí Minh - Thành Phố Thủ Đức",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Hoài Đức",
      "pic": "Lê Như Tánh",
      "order_code": "GYT3XGW7",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Hà Nội - Quận Nam Từ Liêm",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Thanh Oai",
      "pic": "Lê Như Tánh",
      "order_code": "GYT3X7XH",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Hà Nội - Quận Hà Đông",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Thanh Oai",
      "pic": "Lê Như Tánh",
      "order_code": "GYT3XGW6",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Hà Nội - Huyện Mỹ Đức",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Thanh Oai",
      "pic": "Lê Như Tánh",
      "order_code": "GYT3XGWA",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Hà Nội - Huyện Thanh Oai",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "An Dương - Hải Phòng",
      "pic": "Đào Anh Duy",
      "order_code": "GYT3X7XK",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Hải Phòng - Quận Kiến An",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "An Dương - Hải Phòng",
      "pic": "Đào Anh Duy",
      "order_code": "GYT3X7XW",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Hải Phòng - Quận Lê Chân",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Tiên Du - Bắc Ninh",
      "pic": "Nguyễn Mạnh Hưng",
      "order_code": "GYT3XC7N",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Bắc Ninh - Thành phố Bắc Ninh",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Việt Yên - Bắc Giang",
      "pic": "Nguyễn Mạnh Hưng",
      "order_code": "GYT3X7X8",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Bắc Giang - Huyện Hiệp Hòa",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "TP Thái Nguyên - Thái Nguyên",
      "pic": "Nguyễn Mạnh Hưng",
      "order_code": "GYT3X7A6",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thái Nguyên - Thành phố Thái Nguyên",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "TP Thái Nguyên - Thái Nguyên",
      "pic": "Nguyễn Mạnh Hưng",
      "order_code": "GYT3X7AQ",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thái Nguyên - Thị xã Phổ Yên",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "TP Thái Nguyên - Thái Nguyên",
      "pic": "Nguyễn Mạnh Hưng",
      "order_code": "GYT3X7AU",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thái Nguyên - Thành Phố Sông Công",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "TP Lào Cai - Lào Cai",
      "pic": "Nguyễn Sơn Tuấn",
      "order_code": "GYTBTWHV",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Lai Châu - Thành phố Lai Châu",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Dĩ An - Bình Dương",
      "pic": "Trần Như Long",
      "order_code": "GYTTMBV9",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Bình Dương - Thành phố Dĩ An",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Dĩ An - Bình Dương",
      "pic": "Trần Như Long",
      "order_code": "GYTTX3FV",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Bình Dương - Thành phố Dĩ An",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Thuận An - Bình Dương",
      "pic": "Trần Như Long",
      "order_code": "GYTHL9DK",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Bình Dương - Thành phố Thuận An",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "TP Đồng Xoài - Bình Phước",
      "pic": "Trần Như Long",
      "order_code": "GYTTX37E",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Bình Phước - Thành phố Đồng Xoài",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Đức Hòa - Long An",
      "pic": "Trần Hoàng An Khang",
      "order_code": "GYTTMBUU",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Long An - Huyện Đức Hòa",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "TX Cai Lậy - Tiền Giang",
      "pic": "Trần Hoàng An Khang",
      "order_code": "GYTTX3LF",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Tiền Giang - Huyện Cái Bè",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Phan Rang - Ninh Thuận",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTK6PRN",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Ninh Thuận - Thành phố Phan Rang – Tháp Chàm",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Thạch Linh - Hà Tĩnh",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTK6BC4",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hà Tĩnh - Thành phố Hà Tĩnh",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "2: trong ngày mai",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTK6BFB",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Nghệ An - Huyện Quỳnh Lưu",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYT4AF39",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Quận Bình Tân",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Tân Tạo - HCM",
      "pic": "Nguyễn Công Danh",
      "order_code": "GYTTEEG9",
      "action": "giao",
      "client": "ANTA",
      "address": "Hồ Chí Minh - Quận Bình Tân",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Bắc Từ Liêm",
      "pic": "Lê Như Tánh",
      "order_code": "GYTK6PAU",
      "action": "giao",
      "client": "Aqua B2C",
      "address": "Hà Nội - Quận Đống Đa",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Việt Yên - Bắc Giang",
      "pic": "Nguyễn Mạnh Hưng",
      "order_code": "GYT4RPH8",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Bắc Giang - Huyện Lục Nam",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Việt Yên - Bắc Giang",
      "pic": "Nguyễn Mạnh Hưng",
      "order_code": "GYT4RPHY",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Bắc Giang - Thành phố Bắc Giang",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "TP Thái Nguyên - Thái Nguyên",
      "pic": "Nguyễn Mạnh Hưng",
      "order_code": "GYT4RP7X",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thái Nguyên - Thành Phố Sông Công",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Bình Xuyên - Vĩnh Phúc",
      "pic": "Nguyễn Sơn Tuấn",
      "order_code": "GYT3XGWK",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Vĩnh Phúc - Huyện Lập Thạch",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Bình Xuyên - Vĩnh Phúc",
      "pic": "Nguyễn Sơn Tuấn",
      "order_code": "GYT3XGWN",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Vĩnh Phúc - Huyện Bình Xuyên",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "TP Lạng Sơn - Lạng Sơn",
      "pic": "Nguyễn Sơn Tuấn",
      "order_code": "GYT3XGW4",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Lạng Sơn - Huyện Lộc Bình",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Thuận An - Bình Dương",
      "pic": "Trần Như Long",
      "order_code": "GYT4DFXY",
      "action": "giao",
      "client": "ANTA",
      "address": "Bình Dương - Thành phố Thuận An",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "TP Vũng Tàu - BRVT",
      "pic": "Trần Như Long",
      "order_code": "GYT4AFB4",
      "action": "giao",
      "client": "ANTA",
      "address": "Bà Rịa - Vũng Tàu - Thành phố Vũng Tàu",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT4RPHL",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Thiệu Hóa",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT4RPHV",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Triệu Sơn",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT4RPT8",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Thị Xã Nghi Sơn",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT4RPTK",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Quảng Xương",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT4RPTM",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Vĩnh Lộc",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT4RPTR",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Triệu Sơn",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Đông Thọ - Thanh Hoá",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT4RPTT",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Thanh Hóa - Huyện Thọ Xuân",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Liên Chiểu - Đà Nẵng",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKA4EL",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Đà Nẵng - Quận Sơn Trà",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Liên Chiểu - Đà Nẵng",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKAKQ7",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Đà Nẵng - Quận Sơn Trà",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Liên Chiểu - Đà Nẵng",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKAKQ9",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Đà Nẵng - Quận Ngũ Hành Sơn",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Liên Chiểu - Đà Nẵng",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKAKQP",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Đà Nẵng - Quận Cẩm Lệ",
      "inbound_date": "2026-05-26",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Quảng Ngãi - Quảng Ngãi",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKA4E8",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Quảng Ngãi - Huyện Nghĩa Hành",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Quảng Ngãi - Quảng Ngãi",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKA4EE",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Quảng Ngãi - Huyện Tư Nghĩa",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Quảng Ngãi - Quảng Ngãi",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKA4EM",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Quảng Ngãi - Huyện Bình Sơn",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Quảng Ngãi - Quảng Ngãi",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKAKQC",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Quảng Ngãi - Thành phố Quảng Ngãi",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Quảng Ngãi - Quảng Ngãi",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKAKQD",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Quảng Ngãi - Thành phố Quảng Ngãi",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Quảng Ngãi - Quảng Ngãi",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKAKQL",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Quảng Ngãi - Huyện Sơn Tịnh",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Quảng Ngãi - Quảng Ngãi",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKAKQN",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Quảng Ngãi - Huyện Sơn Tịnh",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Quảng Ngãi - Quảng Ngãi",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKAKQT",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Quảng Ngãi - Huyện Sơn Hà",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Quảng Ngãi - Quảng Ngãi",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKAKQU",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Quảng Ngãi - Huyện Mộ Đức",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Quảng Ngãi - Quảng Ngãi",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYTKAKQX",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Quảng Ngãi - Thành phố Quảng Ngãi",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT4RPHD",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Nghệ An - Thành phố Vinh",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT4RPTA",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Nghệ An - Huyện Yên Thành",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    },
    {
      "priority": "3: trong ngày mốt",
      "warehouse": "Vinh - Nghệ An",
      "pic": "Nguyễn Minh Nghị",
      "order_code": "GYT4RPTB",
      "action": "giao",
      "client": "Con Cưng",
      "address": "Nghệ An - Thị xã Hoàng Mai",
      "inbound_date": "2026-05-25",
      "storage_days": "1",
      "appointment_flag": ""
    }
  ]
};
